# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'TestInformationOverview.ui'
#
# Created by: PyQt5 UI code generator 5.14.2
#
# WARNING! All changes made in this file will be lost!
import sys
import sqlite3
import docx
from docx import Document
from docx.shared import Pt, Cm, RGBColor
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QMessageBox, QWidget, QApplication,QMainWindow, QListWidget,QTableWidgetItem, QAction, QVBoxLayout, QTableWidget, QCompleter
from PyQt5.QtSql import *

class Ui_TestOverviewWindow(object):
    def setupUi(self, TestOverviewWindow):
        TestOverviewWindow.setObjectName("TestOverviewWindow")
        TestOverviewWindow.resize(1550, 907)
        TestOverviewWindow.setMinimumSize(QtCore.QSize(1550, 900))
        TestOverviewWindow.setMaximumSize(QtCore.QSize(1550, 907))
        self.verticalLayout_38 = QtWidgets.QVBoxLayout(TestOverviewWindow)
        self.verticalLayout_38.setObjectName("verticalLayout_38")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.verticalLayout_37 = QtWidgets.QVBoxLayout()
        self.verticalLayout_37.setObjectName("verticalLayout_37")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.ReportLBL_Window = QtWidgets.QLabel(TestOverviewWindow)
        self.ReportLBL_Window.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setFamily("Eras Bold ITC")
        font.setPointSize(15)
        self.ReportLBL_Window.setFont(font)
        self.ReportLBL_Window.setObjectName("ReportLBL_Window")
        self.verticalLayout_2.addWidget(self.ReportLBL_Window)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.InformationOverviewTestIDLBL = QtWidgets.QLabel(TestOverviewWindow)
        self.InformationOverviewTestIDLBL.setObjectName("InformationOverviewTestIDLBL")
        self.verticalLayout.addWidget(self.InformationOverviewTestIDLBL)
        self.InformationOverviewTestIDLineEdit = QtWidgets.QLineEdit(TestOverviewWindow)
        self.InformationOverviewTestIDLineEdit.setObjectName("InformationOverviewTestIDLineEdit")
        self.verticalLayout.addWidget(self.InformationOverviewTestIDLineEdit)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.ReportTitleLBL_2_Window = QtWidgets.QLabel(TestOverviewWindow)
        self.ReportTitleLBL_2_Window.setMinimumSize(QtCore.QSize(120, 0))
        self.ReportTitleLBL_2_Window.setMaximumSize(QtCore.QSize(120, 16777215))
        self.ReportTitleLBL_2_Window.setObjectName("ReportTitleLBL_2_Window")
        self.horizontalLayout_6.addWidget(self.ReportTitleLBL_2_Window)
        self.ReportTitleBox_2_Window = QtWidgets.QLineEdit(TestOverviewWindow)
        self.ReportTitleBox_2_Window.setMaximumSize(QtCore.QSize(500, 16777215))
        self.ReportTitleBox_2_Window.setObjectName("ReportTitleBox_2_Window")
        self.horizontalLayout_6.addWidget(self.ReportTitleBox_2_Window)
        self.verticalLayout.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.AssessmentTypeLBL_2_Window = QtWidgets.QLabel(TestOverviewWindow)
        self.AssessmentTypeLBL_2_Window.setMinimumSize(QtCore.QSize(120, 0))
        self.AssessmentTypeLBL_2_Window.setMaximumSize(QtCore.QSize(120, 16777215))
        self.AssessmentTypeLBL_2_Window.setObjectName("AssessmentTypeLBL_2_Window")
        self.horizontalLayout_4.addWidget(self.AssessmentTypeLBL_2_Window)
        self.AssessmentTypeBox_2_Window = QtWidgets.QLineEdit(TestOverviewWindow)
        self.AssessmentTypeBox_2_Window.setMinimumSize(QtCore.QSize(120, 0))
        self.AssessmentTypeBox_2_Window.setMaximumSize(QtCore.QSize(500, 16777215))
        self.AssessmentTypeBox_2_Window.setObjectName("AssessmentTypeBox_2_Window")
        self.horizontalLayout_4.addWidget(self.AssessmentTypeBox_2_Window)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.ScoringTypeLBL_2_Window = QtWidgets.QLabel(TestOverviewWindow)
        self.ScoringTypeLBL_2_Window.setMinimumSize(QtCore.QSize(120, 0))
        self.ScoringTypeLBL_2_Window.setMaximumSize(QtCore.QSize(120, 16777215))
        self.ScoringTypeLBL_2_Window.setObjectName("ScoringTypeLBL_2_Window")
        self.horizontalLayout_3.addWidget(self.ScoringTypeLBL_2_Window)
        self.ScoringTypeBox_2_Window = QtWidgets.QLineEdit(TestOverviewWindow)
        self.ScoringTypeBox_2_Window.setMaximumSize(QtCore.QSize(500, 16777215))
        self.ScoringTypeBox_2_Window.setObjectName("ScoringTypeBox_2_Window")
        self.horizontalLayout_3.addWidget(self.ScoringTypeBox_2_Window)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.FullCompNameLBL_2_Window = QtWidgets.QLabel(TestOverviewWindow)
        self.FullCompNameLBL_2_Window.setMinimumSize(QtCore.QSize(120, 0))
        self.FullCompNameLBL_2_Window.setMaximumSize(QtCore.QSize(120, 16777215))
        self.FullCompNameLBL_2_Window.setObjectName("FullCompNameLBL_2_Window")
        self.horizontalLayout_2.addWidget(self.FullCompNameLBL_2_Window)
        self.FullCompNameBox_2_Window = QtWidgets.QLineEdit(TestOverviewWindow)
        self.FullCompNameBox_2_Window.setMaximumSize(QtCore.QSize(500, 16777215))
        self.FullCompNameBox_2_Window.setObjectName("FullCompNameBox_2_Window")
        self.horizontalLayout_2.addWidget(self.FullCompNameBox_2_Window)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.ShortCompNameLBL_2_Window = QtWidgets.QLabel(TestOverviewWindow)
        self.ShortCompNameLBL_2_Window.setMinimumSize(QtCore.QSize(120, 0))
        self.ShortCompNameLBL_2_Window.setMaximumSize(QtCore.QSize(120, 16777215))
        self.ShortCompNameLBL_2_Window.setObjectName("ShortCompNameLBL_2_Window")
        self.horizontalLayout.addWidget(self.ShortCompNameLBL_2_Window)
        self.ShortCompNameBox_2_Window = QtWidgets.QLineEdit(TestOverviewWindow)
        self.ShortCompNameBox_2_Window.setMaximumSize(QtCore.QSize(500, 16777215))
        self.ShortCompNameBox_2_Window.setObjectName("ShortCompNameBox_2_Window")
        self.horizontalLayout.addWidget(self.ShortCompNameBox_2_Window)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        spacerItem = QtWidgets.QSpacerItem(20, 80, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_2.addItem(spacerItem)
        self.horizontalLayout_7.addLayout(self.verticalLayout_2)
        self.line = QtWidgets.QFrame(TestOverviewWindow)
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.horizontalLayout_7.addWidget(self.line)
        self.horizontalLayout_11.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.ContactCompany_Window = QtWidgets.QLabel(TestOverviewWindow)
        self.ContactCompany_Window.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setFamily("Eras Bold ITC")
        font.setPointSize(15)
        self.ContactCompany_Window.setFont(font)
        self.ContactCompany_Window.setObjectName("ContactCompany_Window")
        self.verticalLayout_3.addWidget(self.ContactCompany_Window)
        self.verticalLayout_25 = QtWidgets.QVBoxLayout()
        self.verticalLayout_25.setObjectName("verticalLayout_25")
        self.horizontalLayout_39 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_39.setObjectName("horizontalLayout_39")
        self.ContactTitleLBL_2_Window = QtWidgets.QLabel(TestOverviewWindow)
        self.ContactTitleLBL_2_Window.setMinimumSize(QtCore.QSize(120, 0))
        self.ContactTitleLBL_2_Window.setMaximumSize(QtCore.QSize(120, 16777215))
        self.ContactTitleLBL_2_Window.setObjectName("ContactTitleLBL_2_Window")
        self.horizontalLayout_39.addWidget(self.ContactTitleLBL_2_Window)
        self.ContactTitleBox_2_Window = QtWidgets.QLineEdit(TestOverviewWindow)
        self.ContactTitleBox_2_Window.setMaximumSize(QtCore.QSize(500, 16777215))
        self.ContactTitleBox_2_Window.setObjectName("ContactTitleBox_2_Window")
        self.horizontalLayout_39.addWidget(self.ContactTitleBox_2_Window)
        self.verticalLayout_25.addLayout(self.horizontalLayout_39)
        self.horizontalLayout_38 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_38.setObjectName("horizontalLayout_38")
        self.ContactNameLBL_2_Window = QtWidgets.QLabel(TestOverviewWindow)
        self.ContactNameLBL_2_Window.setMinimumSize(QtCore.QSize(120, 0))
        self.ContactNameLBL_2_Window.setMaximumSize(QtCore.QSize(120, 16777215))
        self.ContactNameLBL_2_Window.setObjectName("ContactNameLBL_2_Window")
        self.horizontalLayout_38.addWidget(self.ContactNameLBL_2_Window)
        self.ContactNameBox_2_Window = QtWidgets.QLineEdit(TestOverviewWindow)
        self.ContactNameBox_2_Window.setMaximumSize(QtCore.QSize(500, 16777215))
        self.ContactNameBox_2_Window.setObjectName("ContactNameBox_2_Window")
        self.horizontalLayout_38.addWidget(self.ContactNameBox_2_Window)
        self.verticalLayout_25.addLayout(self.horizontalLayout_38)
        self.horizontalLayout_37 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_37.setObjectName("horizontalLayout_37")
        self.ContactTelephoneLBL_Window = QtWidgets.QLabel(TestOverviewWindow)
        self.ContactTelephoneLBL_Window.setMinimumSize(QtCore.QSize(120, 0))
        self.ContactTelephoneLBL_Window.setMaximumSize(QtCore.QSize(120, 16777215))
        self.ContactTelephoneLBL_Window.setObjectName("ContactTelephoneLBL_Window")
        self.horizontalLayout_37.addWidget(self.ContactTelephoneLBL_Window)
        self.ContactTelephoneBox_Window = QtWidgets.QLineEdit(TestOverviewWindow)
        self.ContactTelephoneBox_Window.setMinimumSize(QtCore.QSize(120, 0))
        self.ContactTelephoneBox_Window.setMaximumSize(QtCore.QSize(500, 16777215))
        self.ContactTelephoneBox_Window.setObjectName("ContactTelephoneBox_Window")
        self.horizontalLayout_37.addWidget(self.ContactTelephoneBox_Window)
        self.verticalLayout_25.addLayout(self.horizontalLayout_37)
        self.horizontalLayout_36 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_36.setObjectName("horizontalLayout_36")
        self.ContactEmailLBL_2_Window = QtWidgets.QLabel(TestOverviewWindow)
        self.ContactEmailLBL_2_Window.setMinimumSize(QtCore.QSize(120, 0))
        self.ContactEmailLBL_2_Window.setMaximumSize(QtCore.QSize(120, 16777215))
        self.ContactEmailLBL_2_Window.setObjectName("ContactEmailLBL_2_Window")
        self.horizontalLayout_36.addWidget(self.ContactEmailLBL_2_Window)
        self.ContactEmailBox_2_Window = QtWidgets.QLineEdit(TestOverviewWindow)
        self.ContactEmailBox_2_Window.setMaximumSize(QtCore.QSize(500, 16777215))
        self.ContactEmailBox_2_Window.setObjectName("ContactEmailBox_2_Window")
        self.horizontalLayout_36.addWidget(self.ContactEmailBox_2_Window)
        self.verticalLayout_25.addLayout(self.horizontalLayout_36)
        self.horizontalLayout_35 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_35.setObjectName("horizontalLayout_35")
        self.CompWebsiteLBL_2_Window = QtWidgets.QLabel(TestOverviewWindow)
        self.CompWebsiteLBL_2_Window.setMinimumSize(QtCore.QSize(120, 0))
        self.CompWebsiteLBL_2_Window.setMaximumSize(QtCore.QSize(120, 16777215))
        self.CompWebsiteLBL_2_Window.setObjectName("CompWebsiteLBL_2_Window")
        self.horizontalLayout_35.addWidget(self.CompWebsiteLBL_2_Window)
        self.CompWebsiteBox_2_Window = QtWidgets.QLineEdit(TestOverviewWindow)
        self.CompWebsiteBox_2_Window.setMaximumSize(QtCore.QSize(500, 16777215))
        self.CompWebsiteBox_2_Window.setObjectName("CompWebsiteBox_2_Window")
        self.horizontalLayout_35.addWidget(self.CompWebsiteBox_2_Window)
        self.verticalLayout_25.addLayout(self.horizontalLayout_35)
        self.horizontalLayout_34 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_34.setObjectName("horizontalLayout_34")
        self.CompAddressLBL_2_Window = QtWidgets.QLabel(TestOverviewWindow)
        self.CompAddressLBL_2_Window.setMinimumSize(QtCore.QSize(120, 0))
        self.CompAddressLBL_2_Window.setMaximumSize(QtCore.QSize(120, 16777215))
        self.CompAddressLBL_2_Window.setObjectName("CompAddressLBL_2_Window")
        self.horizontalLayout_34.addWidget(self.CompAddressLBL_2_Window)
        self.CompAddressBox_2_Window = QtWidgets.QLineEdit(TestOverviewWindow)
        self.CompAddressBox_2_Window.setMaximumSize(QtCore.QSize(500, 16777215))
        self.CompAddressBox_2_Window.setObjectName("CompAddressBox_2_Window")
        self.horizontalLayout_34.addWidget(self.CompAddressBox_2_Window)
        self.verticalLayout_25.addLayout(self.horizontalLayout_34)
        self.horizontalLayout_33 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_33.setObjectName("horizontalLayout_33")
        self.CompCityLBL_2_Window = QtWidgets.QLabel(TestOverviewWindow)
        self.CompCityLBL_2_Window.setMinimumSize(QtCore.QSize(120, 0))
        self.CompCityLBL_2_Window.setMaximumSize(QtCore.QSize(120, 16777215))
        self.CompCityLBL_2_Window.setObjectName("CompCityLBL_2_Window")
        self.horizontalLayout_33.addWidget(self.CompCityLBL_2_Window)
        self.CompCityBox_2_Window = QtWidgets.QLineEdit(TestOverviewWindow)
        self.CompCityBox_2_Window.setMaximumSize(QtCore.QSize(500, 16777215))
        self.CompCityBox_2_Window.setObjectName("CompCityBox_2_Window")
        self.horizontalLayout_33.addWidget(self.CompCityBox_2_Window)
        self.verticalLayout_25.addLayout(self.horizontalLayout_33)
        self.horizontalLayout_32 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_32.setObjectName("horizontalLayout_32")
        self.StateLBL_2_Window = QtWidgets.QLabel(TestOverviewWindow)
        self.StateLBL_2_Window.setMinimumSize(QtCore.QSize(120, 0))
        self.StateLBL_2_Window.setMaximumSize(QtCore.QSize(120, 16777215))
        self.StateLBL_2_Window.setObjectName("StateLBL_2_Window")
        self.horizontalLayout_32.addWidget(self.StateLBL_2_Window)
        self.StateBox_2_Window = QtWidgets.QLineEdit(TestOverviewWindow)
        self.StateBox_2_Window.setMaximumSize(QtCore.QSize(500, 16777215))
        self.StateBox_2_Window.setObjectName("StateBox_2_Window")
        self.horizontalLayout_32.addWidget(self.StateBox_2_Window)
        self.verticalLayout_25.addLayout(self.horizontalLayout_32)
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.CompPostCodeLBL_2_Window = QtWidgets.QLabel(TestOverviewWindow)
        self.CompPostCodeLBL_2_Window.setMinimumSize(QtCore.QSize(120, 0))
        self.CompPostCodeLBL_2_Window.setMaximumSize(QtCore.QSize(120, 16777215))
        self.CompPostCodeLBL_2_Window.setObjectName("CompPostCodeLBL_2_Window")
        self.horizontalLayout_16.addWidget(self.CompPostCodeLBL_2_Window)
        self.CompPostCodeBox_2_Window = QtWidgets.QLineEdit(TestOverviewWindow)
        self.CompPostCodeBox_2_Window.setMaximumSize(QtCore.QSize(500, 16777215))
        self.CompPostCodeBox_2_Window.setObjectName("CompPostCodeBox_2_Window")
        self.horizontalLayout_16.addWidget(self.CompPostCodeBox_2_Window)
        self.verticalLayout_25.addLayout(self.horizontalLayout_16)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_25.addItem(spacerItem1)
        self.verticalLayout_3.addLayout(self.verticalLayout_25)
        self.horizontalLayout_8.addLayout(self.verticalLayout_3)
        self.line_2 = QtWidgets.QFrame(TestOverviewWindow)
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.horizontalLayout_8.addWidget(self.line_2)
        self.horizontalLayout_11.addLayout(self.horizontalLayout_8)
        self.verticalLayout_12 = QtWidgets.QVBoxLayout()
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.TesterLBL_Window = QtWidgets.QLabel(TestOverviewWindow)
        self.TesterLBL_Window.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setFamily("Eras Bold ITC")
        font.setPointSize(15)
        self.TesterLBL_Window.setFont(font)
        self.TesterLBL_Window.setObjectName("TesterLBL_Window")
        self.verticalLayout_12.addWidget(self.TesterLBL_Window)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_47 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_47.setObjectName("horizontalLayout_47")
        self.ConsultantCompanyNameLBL_Window = QtWidgets.QLabel(TestOverviewWindow)
        self.ConsultantCompanyNameLBL_Window.setMinimumSize(QtCore.QSize(120, 0))
        self.ConsultantCompanyNameLBL_Window.setMaximumSize(QtCore.QSize(120, 16777215))
        self.ConsultantCompanyNameLBL_Window.setObjectName("ConsultantCompanyNameLBL_Window")
        self.horizontalLayout_47.addWidget(self.ConsultantCompanyNameLBL_Window)
        self.ConsultantCompanyNameBox_Window = QtWidgets.QLineEdit(TestOverviewWindow)
        self.ConsultantCompanyNameBox_Window.setMaximumSize(QtCore.QSize(500, 16777215))
        self.ConsultantCompanyNameBox_Window.setObjectName("ConsultantCompanyNameBox_Window")
        self.horizontalLayout_47.addWidget(self.ConsultantCompanyNameBox_Window)
        self.verticalLayout_4.addLayout(self.horizontalLayout_47)
        self.horizontalLayout_45 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_45.setObjectName("horizontalLayout_45")
        self.ConsultantTitleLBL_Window = QtWidgets.QLabel(TestOverviewWindow)
        self.ConsultantTitleLBL_Window.setMinimumSize(QtCore.QSize(120, 0))
        self.ConsultantTitleLBL_Window.setMaximumSize(QtCore.QSize(120, 16777215))
        self.ConsultantTitleLBL_Window.setObjectName("ConsultantTitleLBL_Window")
        self.horizontalLayout_45.addWidget(self.ConsultantTitleLBL_Window)
        self.ConsultantTitleBox_Window = QtWidgets.QLineEdit(TestOverviewWindow)
        self.ConsultantTitleBox_Window.setMaximumSize(QtCore.QSize(500, 16777215))
        self.ConsultantTitleBox_Window.setObjectName("ConsultantTitleBox_Window")
        self.horizontalLayout_45.addWidget(self.ConsultantTitleBox_Window)
        self.verticalLayout_4.addLayout(self.horizontalLayout_45)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.TesterName_NewWindowLBL = QtWidgets.QLabel(TestOverviewWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.TesterName_NewWindowLBL.sizePolicy().hasHeightForWidth())
        self.TesterName_NewWindowLBL.setSizePolicy(sizePolicy)
        self.TesterName_NewWindowLBL.setMaximumSize(QtCore.QSize(120, 16777215))
        self.TesterName_NewWindowLBL.setObjectName("TesterName_NewWindowLBL")
        self.horizontalLayout_5.addWidget(self.TesterName_NewWindowLBL)
        self.TesterName_NewWindow = QtWidgets.QLineEdit(TestOverviewWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.TesterName_NewWindow.sizePolicy().hasHeightForWidth())
        self.TesterName_NewWindow.setSizePolicy(sizePolicy)
        self.TesterName_NewWindow.setMaximumSize(QtCore.QSize(500, 16777215))
        self.TesterName_NewWindow.setObjectName("TesterName_NewWindow")
        self.horizontalLayout_5.addWidget(self.TesterName_NewWindow)
        self.verticalLayout_4.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_44 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_44.setObjectName("horizontalLayout_44")
        self.ConsultantTelephoneLBL_Window = QtWidgets.QLabel(TestOverviewWindow)
        self.ConsultantTelephoneLBL_Window.setMinimumSize(QtCore.QSize(120, 0))
        self.ConsultantTelephoneLBL_Window.setMaximumSize(QtCore.QSize(120, 16777215))
        self.ConsultantTelephoneLBL_Window.setObjectName("ConsultantTelephoneLBL_Window")
        self.horizontalLayout_44.addWidget(self.ConsultantTelephoneLBL_Window)
        self.ConsultantTelephoneBox_Window = QtWidgets.QLineEdit(TestOverviewWindow)
        self.ConsultantTelephoneBox_Window.setMaximumSize(QtCore.QSize(500, 16777215))
        self.ConsultantTelephoneBox_Window.setObjectName("ConsultantTelephoneBox_Window")
        self.horizontalLayout_44.addWidget(self.ConsultantTelephoneBox_Window)
        self.verticalLayout_4.addLayout(self.horizontalLayout_44)
        self.horizontalLayout_43 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_43.setObjectName("horizontalLayout_43")
        self.ConsultantEmailLBL_Window = QtWidgets.QLabel(TestOverviewWindow)
        self.ConsultantEmailLBL_Window.setMinimumSize(QtCore.QSize(120, 0))
        self.ConsultantEmailLBL_Window.setMaximumSize(QtCore.QSize(120, 16777215))
        self.ConsultantEmailLBL_Window.setObjectName("ConsultantEmailLBL_Window")
        self.horizontalLayout_43.addWidget(self.ConsultantEmailLBL_Window)
        self.ConsultantEmailBox_Window = QtWidgets.QLineEdit(TestOverviewWindow)
        self.ConsultantEmailBox_Window.setMaximumSize(QtCore.QSize(500, 16777215))
        self.ConsultantEmailBox_Window.setObjectName("ConsultantEmailBox_Window")
        self.horizontalLayout_43.addWidget(self.ConsultantEmailBox_Window)
        self.verticalLayout_4.addLayout(self.horizontalLayout_43)
        self.horizontalLayout_42 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_42.setObjectName("horizontalLayout_42")
        self.ConsultantAddressLBL_Window = QtWidgets.QLabel(TestOverviewWindow)
        self.ConsultantAddressLBL_Window.setMinimumSize(QtCore.QSize(120, 0))
        self.ConsultantAddressLBL_Window.setMaximumSize(QtCore.QSize(120, 16777215))
        self.ConsultantAddressLBL_Window.setObjectName("ConsultantAddressLBL_Window")
        self.horizontalLayout_42.addWidget(self.ConsultantAddressLBL_Window)
        self.ConsultantBusinessAddressBox_Window = QtWidgets.QLineEdit(TestOverviewWindow)
        self.ConsultantBusinessAddressBox_Window.setMaximumSize(QtCore.QSize(500, 16777215))
        self.ConsultantBusinessAddressBox_Window.setObjectName("ConsultantBusinessAddressBox_Window")
        self.horizontalLayout_42.addWidget(self.ConsultantBusinessAddressBox_Window)
        self.verticalLayout_4.addLayout(self.horizontalLayout_42)
        self.horizontalLayout_41 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_41.setObjectName("horizontalLayout_41")
        self.ConsultantCityLBL_Window = QtWidgets.QLabel(TestOverviewWindow)
        self.ConsultantCityLBL_Window.setMinimumSize(QtCore.QSize(120, 0))
        self.ConsultantCityLBL_Window.setMaximumSize(QtCore.QSize(120, 16777215))
        self.ConsultantCityLBL_Window.setObjectName("ConsultantCityLBL_Window")
        self.horizontalLayout_41.addWidget(self.ConsultantCityLBL_Window)
        self.ConsultantCityBox_Window = QtWidgets.QLineEdit(TestOverviewWindow)
        self.ConsultantCityBox_Window.setMaximumSize(QtCore.QSize(500, 16777215))
        self.ConsultantCityBox_Window.setObjectName("ConsultantCityBox_Window")
        self.horizontalLayout_41.addWidget(self.ConsultantCityBox_Window)
        self.verticalLayout_4.addLayout(self.horizontalLayout_41)
        self.horizontalLayout_40 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_40.setObjectName("horizontalLayout_40")
        self.ConsultantWebsiteLBL_Window = QtWidgets.QLabel(TestOverviewWindow)
        self.ConsultantWebsiteLBL_Window.setMinimumSize(QtCore.QSize(120, 0))
        self.ConsultantWebsiteLBL_Window.setMaximumSize(QtCore.QSize(120, 16777215))
        self.ConsultantWebsiteLBL_Window.setObjectName("ConsultantWebsiteLBL_Window")
        self.horizontalLayout_40.addWidget(self.ConsultantWebsiteLBL_Window)
        self.ConsultantWebsiteBox_Window = QtWidgets.QLineEdit(TestOverviewWindow)
        self.ConsultantWebsiteBox_Window.setMaximumSize(QtCore.QSize(500, 16777215))
        self.ConsultantWebsiteBox_Window.setObjectName("ConsultantWebsiteBox_Window")
        self.horizontalLayout_40.addWidget(self.ConsultantWebsiteBox_Window)
        self.verticalLayout_4.addLayout(self.horizontalLayout_40)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem2)
        self.verticalLayout_12.addLayout(self.verticalLayout_4)
        self.horizontalLayout_11.addLayout(self.verticalLayout_12)
        self.verticalLayout_37.addLayout(self.horizontalLayout_11)
        self.verticalLayout_36 = QtWidgets.QVBoxLayout()
        self.verticalLayout_36.setObjectName("verticalLayout_36")
        spacerItem3 = QtWidgets.QSpacerItem(828, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_36.addItem(spacerItem3)
        self.line_3 = QtWidgets.QFrame(TestOverviewWindow)
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.verticalLayout_36.addWidget(self.line_3)
        spacerItem4 = QtWidgets.QSpacerItem(826, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_36.addItem(spacerItem4)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.verticalLayout_30 = QtWidgets.QVBoxLayout()
        self.verticalLayout_30.setObjectName("verticalLayout_30")
        self.CVEInformation_Window = QtWidgets.QLabel(TestOverviewWindow)
        self.CVEInformation_Window.setMaximumSize(QtCore.QSize(200, 30))
        font = QtGui.QFont()
        font.setFamily("Eras Bold ITC")
        font.setPointSize(15)
        self.CVEInformation_Window.setFont(font)
        self.CVEInformation_Window.setObjectName("CVEInformation_Window")
        self.verticalLayout_30.addWidget(self.CVEInformation_Window)
        self.verticalLayout_15 = QtWidgets.QVBoxLayout()
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.verticalLayout_14 = QtWidgets.QVBoxLayout()
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.CVENameLBLDisplay_Window = QtWidgets.QLabel(TestOverviewWindow)
        self.CVENameLBLDisplay_Window.setMaximumSize(QtCore.QSize(100, 25))
        self.CVENameLBLDisplay_Window.setObjectName("CVENameLBLDisplay_Window")
        self.verticalLayout_14.addWidget(self.CVENameLBLDisplay_Window)
        self.CVENameTextEdit_Window = QtWidgets.QTextEdit(TestOverviewWindow)
        self.CVENameTextEdit_Window.setMaximumSize(QtCore.QSize(500, 25))
        self.CVENameTextEdit_Window.setObjectName("CVENameTextEdit_Window")
        self.verticalLayout_14.addWidget(self.CVENameTextEdit_Window)
        self.verticalLayout_15.addLayout(self.verticalLayout_14)
        self.verticalLayout_13 = QtWidgets.QVBoxLayout()
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.CVSSLBLDisplay_Window = QtWidgets.QLabel(TestOverviewWindow)
        self.CVSSLBLDisplay_Window.setMaximumSize(QtCore.QSize(100, 25))
        self.CVSSLBLDisplay_Window.setObjectName("CVSSLBLDisplay_Window")
        self.verticalLayout_13.addWidget(self.CVSSLBLDisplay_Window)
        self.CVSSTextEdit_Window = QtWidgets.QTextEdit(TestOverviewWindow)
        self.CVSSTextEdit_Window.setMaximumSize(QtCore.QSize(500, 25))
        self.CVSSTextEdit_Window.setObjectName("CVSSTextEdit_Window")
        self.verticalLayout_13.addWidget(self.CVSSTextEdit_Window)
        self.verticalLayout_15.addLayout(self.verticalLayout_13)
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.CVEDateLBLDisplay_Window = QtWidgets.QLabel(TestOverviewWindow)
        self.CVEDateLBLDisplay_Window.setMaximumSize(QtCore.QSize(100, 25))
        self.CVEDateLBLDisplay_Window.setObjectName("CVEDateLBLDisplay_Window")
        self.verticalLayout_7.addWidget(self.CVEDateLBLDisplay_Window)
        self.CVEDateTextEdit_Window = QtWidgets.QTextEdit(TestOverviewWindow)
        self.CVEDateTextEdit_Window.setMaximumSize(QtCore.QSize(200, 25))
        self.CVEDateTextEdit_Window.setObjectName("CVEDateTextEdit_Window")
        self.verticalLayout_7.addWidget(self.CVEDateTextEdit_Window)
        self.verticalLayout_15.addLayout(self.verticalLayout_7)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.CVECriticalRatingLBLDisplay_Window = QtWidgets.QLabel(TestOverviewWindow)
        self.CVECriticalRatingLBLDisplay_Window.setMaximumSize(QtCore.QSize(100, 25))
        self.CVECriticalRatingLBLDisplay_Window.setObjectName("CVECriticalRatingLBLDisplay_Window")
        self.verticalLayout_6.addWidget(self.CVECriticalRatingLBLDisplay_Window)
        self.CVECriticalRatingTextEdit_Window = QtWidgets.QTextEdit(TestOverviewWindow)
        self.CVECriticalRatingTextEdit_Window.setMaximumSize(QtCore.QSize(200, 25))
        self.CVECriticalRatingTextEdit_Window.setObjectName("CVECriticalRatingTextEdit_Window")
        self.verticalLayout_6.addWidget(self.CVECriticalRatingTextEdit_Window)
        self.verticalLayout_15.addLayout(self.verticalLayout_6)
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.CVEDescriptionLBLDisplay_Window = QtWidgets.QLabel(TestOverviewWindow)
        self.CVEDescriptionLBLDisplay_Window.setMaximumSize(QtCore.QSize(100, 25))
        self.CVEDescriptionLBLDisplay_Window.setObjectName("CVEDescriptionLBLDisplay_Window")
        self.verticalLayout_8.addWidget(self.CVEDescriptionLBLDisplay_Window)
        self.CVEDescriptionTextEdit_Window = QtWidgets.QTextEdit(TestOverviewWindow)
        self.CVEDescriptionTextEdit_Window.setMinimumSize(QtCore.QSize(200, 150))
        self.CVEDescriptionTextEdit_Window.setMaximumSize(QtCore.QSize(500, 150))
        self.CVEDescriptionTextEdit_Window.setReadOnly(True)
        self.CVEDescriptionTextEdit_Window.setObjectName("CVEDescriptionTextEdit_Window")
        self.verticalLayout_8.addWidget(self.CVEDescriptionTextEdit_Window)
        self.verticalLayout_15.addLayout(self.verticalLayout_8)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.CVERemediationLBLDisplay_Window = QtWidgets.QLabel(TestOverviewWindow)
        self.CVERemediationLBLDisplay_Window.setMaximumSize(QtCore.QSize(100, 25))
        self.CVERemediationLBLDisplay_Window.setObjectName("CVERemediationLBLDisplay_Window")
        self.verticalLayout_5.addWidget(self.CVERemediationLBLDisplay_Window)
        self.CVERemediationTextEdit_Window = QtWidgets.QTextEdit(TestOverviewWindow)
        self.CVERemediationTextEdit_Window.setMinimumSize(QtCore.QSize(200, 100))
        self.CVERemediationTextEdit_Window.setMaximumSize(QtCore.QSize(500, 100))
        self.CVERemediationTextEdit_Window.setObjectName("CVERemediationTextEdit_Window")
        self.verticalLayout_5.addWidget(self.CVERemediationTextEdit_Window)
        self.verticalLayout_15.addLayout(self.verticalLayout_5)
        spacerItem5 = QtWidgets.QSpacerItem(20, 200, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_15.addItem(spacerItem5)
        self.verticalLayout_30.addLayout(self.verticalLayout_15)
        self.horizontalLayout_9.addLayout(self.verticalLayout_30)
        self.line_4 = QtWidgets.QFrame(TestOverviewWindow)
        self.line_4.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.horizontalLayout_9.addWidget(self.line_4)
        self.verticalLayout_35 = QtWidgets.QVBoxLayout()
        self.verticalLayout_35.setObjectName("verticalLayout_35")
        self.scrollArea_2 = QtWidgets.QScrollArea(TestOverviewWindow)
        self.scrollArea_2.setMinimumSize(QtCore.QSize(500, 550))
        self.scrollArea_2.setMaximumSize(QtCore.QSize(500, 700))
        self.scrollArea_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.scrollArea_2.setFrameShadow(QtWidgets.QFrame.Plain)
        self.scrollArea_2.setWidgetResizable(True)
        self.scrollArea_2.setObjectName("scrollArea_2")
        self.scrollAreaWidgetContents_2 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 500, 550))
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        self.verticalLayout_40 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents_2)
        self.verticalLayout_40.setObjectName("verticalLayout_40")
        self.verticalLayout_39 = QtWidgets.QVBoxLayout()
        self.verticalLayout_39.setObjectName("verticalLayout_39")
        self.FindingsInformation_Window = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.FindingsInformation_Window.setMaximumSize(QtCore.QSize(300, 30))
        font = QtGui.QFont()
        font.setFamily("Eras Bold ITC")
        font.setPointSize(15)
        self.FindingsInformation_Window.setFont(font)
        self.FindingsInformation_Window.setObjectName("FindingsInformation_Window")
        self.verticalLayout_39.addWidget(self.FindingsInformation_Window)
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.verticalLayout_34 = QtWidgets.QVBoxLayout()
        self.verticalLayout_34.setObjectName("verticalLayout_34")
        self.selectyourfinding_Window = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.selectyourfinding_Window.setMinimumSize(QtCore.QSize(120, 20))
        self.selectyourfinding_Window.setMaximumSize(QtCore.QSize(120, 20))
        self.selectyourfinding_Window.setObjectName("selectyourfinding_Window")
        self.verticalLayout_34.addWidget(self.selectyourfinding_Window)
        self.FindingsListWidget_Window = QtWidgets.QListWidget(self.scrollAreaWidgetContents_2)
        self.FindingsListWidget_Window.setMinimumSize(QtCore.QSize(200, 170))
        self.FindingsListWidget_Window.setMaximumSize(QtCore.QSize(200, 170))
        self.FindingsListWidget_Window.setObjectName("FindingsListWidget_Window")
        self.verticalLayout_34.addWidget(self.FindingsListWidget_Window)
        self.LoadFindings_WindowBTN = QtWidgets.QPushButton(self.scrollAreaWidgetContents_2)
        self.LoadFindings_WindowBTN.setMinimumSize(QtCore.QSize(0, 30))
        self.LoadFindings_WindowBTN.setMaximumSize(QtCore.QSize(100, 30))
        self.LoadFindings_WindowBTN.setObjectName("LoadFindings_WindowBTN")
        self.verticalLayout_34.addWidget(self.LoadFindings_WindowBTN)
        self.horizontalLayout_14.addLayout(self.verticalLayout_34)
        self.verticalLayout_33 = QtWidgets.QVBoxLayout()
        self.verticalLayout_33.setObjectName("verticalLayout_33")
        self.verticalLayout_32 = QtWidgets.QVBoxLayout()
        self.verticalLayout_32.setObjectName("verticalLayout_32")
        self.searchLBL = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.searchLBL.setMinimumSize(QtCore.QSize(60, 0))
        self.searchLBL.setMaximumSize(QtCore.QSize(60, 20))
        self.searchLBL.setObjectName("searchLBL")
        self.verticalLayout_32.addWidget(self.searchLBL)
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.searchbarLineEdit = QtWidgets.QLineEdit(self.scrollAreaWidgetContents_2)
        self.searchbarLineEdit.setMinimumSize(QtCore.QSize(150, 0))
        self.searchbarLineEdit.setMaximumSize(QtCore.QSize(200, 30))
        self.searchbarLineEdit.setObjectName("searchbarLineEdit")
        self.horizontalLayout_13.addWidget(self.searchbarLineEdit)
        self.SearchBarBTN = QtWidgets.QPushButton(self.scrollAreaWidgetContents_2)
        self.SearchBarBTN.setObjectName("SearchBarBTN")
        self.horizontalLayout_13.addWidget(self.SearchBarBTN)
        self.verticalLayout_32.addLayout(self.horizontalLayout_13)
        self.verticalLayout_33.addLayout(self.verticalLayout_32)
        self.line_6 = QtWidgets.QFrame(self.scrollAreaWidgetContents_2)
        self.line_6.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_6.setObjectName("line_6")
        self.verticalLayout_33.addWidget(self.line_6)
        self.verticalLayout_31 = QtWidgets.QVBoxLayout()
        self.verticalLayout_31.setObjectName("verticalLayout_31")
        self.verticalLayout_28 = QtWidgets.QVBoxLayout()
        self.verticalLayout_28.setObjectName("verticalLayout_28")
        self.NameYourFindingLBL_Window = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.NameYourFindingLBL_Window.setMaximumSize(QtCore.QSize(130, 25))
        self.NameYourFindingLBL_Window.setObjectName("NameYourFindingLBL_Window")
        self.verticalLayout_28.addWidget(self.NameYourFindingLBL_Window)
        self.NameYourFindingTextEdit_Window = QtWidgets.QTextEdit(self.scrollAreaWidgetContents_2)
        self.NameYourFindingTextEdit_Window.setMaximumSize(QtCore.QSize(500, 25))
        self.NameYourFindingTextEdit_Window.setObjectName("NameYourFindingTextEdit_Window")
        self.verticalLayout_28.addWidget(self.NameYourFindingTextEdit_Window)
        self.verticalLayout_31.addLayout(self.verticalLayout_28)
        self.verticalLayout_16 = QtWidgets.QVBoxLayout()
        self.verticalLayout_16.setObjectName("verticalLayout_16")
        self.NewFindingCriticalityLBL_Window = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.NewFindingCriticalityLBL_Window.setMaximumSize(QtCore.QSize(120, 30))
        self.NewFindingCriticalityLBL_Window.setObjectName("NewFindingCriticalityLBL_Window")
        self.verticalLayout_16.addWidget(self.NewFindingCriticalityLBL_Window)
        self.NewFindingCriticalityTextEdit_Window = QtWidgets.QTextEdit(self.scrollAreaWidgetContents_2)
        self.NewFindingCriticalityTextEdit_Window.setMaximumSize(QtCore.QSize(500, 25))
        self.NewFindingCriticalityTextEdit_Window.setObjectName("NewFindingCriticalityTextEdit_Window")
        self.verticalLayout_16.addWidget(self.NewFindingCriticalityTextEdit_Window)
        self.verticalLayout_31.addLayout(self.verticalLayout_16)
        self.verticalLayout_11 = QtWidgets.QVBoxLayout()
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.NewfindingTypeLBL_Window = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.NewfindingTypeLBL_Window.setMaximumSize(QtCore.QSize(120, 16777215))
        self.NewfindingTypeLBL_Window.setObjectName("NewfindingTypeLBL_Window")
        self.verticalLayout_11.addWidget(self.NewfindingTypeLBL_Window)
        self.NewfindingTypeTextEdit_Window = QtWidgets.QTextEdit(self.scrollAreaWidgetContents_2)
        self.NewfindingTypeTextEdit_Window.setMinimumSize(QtCore.QSize(200, 0))
        self.NewfindingTypeTextEdit_Window.setMaximumSize(QtCore.QSize(500, 25))
        self.NewfindingTypeTextEdit_Window.setObjectName("NewfindingTypeTextEdit_Window")
        self.verticalLayout_11.addWidget(self.NewfindingTypeTextEdit_Window)
        self.verticalLayout_31.addLayout(self.verticalLayout_11)
        self.verticalLayout_33.addLayout(self.verticalLayout_31)
        self.horizontalLayout_14.addLayout(self.verticalLayout_33)
        self.verticalLayout_39.addLayout(self.horizontalLayout_14)
        self.verticalLayout_29 = QtWidgets.QVBoxLayout()
        self.verticalLayout_29.setObjectName("verticalLayout_29")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout()
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.NewFindingDescriptionLBL_Window = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.NewFindingDescriptionLBL_Window.setMaximumSize(QtCore.QSize(120, 16777215))
        self.NewFindingDescriptionLBL_Window.setObjectName("NewFindingDescriptionLBL_Window")
        self.verticalLayout_10.addWidget(self.NewFindingDescriptionLBL_Window)
        self.NewFindingDescriptionTextEdit_Window = QtWidgets.QTextEdit(self.scrollAreaWidgetContents_2)
        self.NewFindingDescriptionTextEdit_Window.setMaximumSize(QtCore.QSize(500, 130))
        self.NewFindingDescriptionTextEdit_Window.setObjectName("NewFindingDescriptionTextEdit_Window")
        self.verticalLayout_10.addWidget(self.NewFindingDescriptionTextEdit_Window)
        self.verticalLayout_29.addLayout(self.verticalLayout_10)
        self.verticalLayout_9 = QtWidgets.QVBoxLayout()
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.NewFindingRemediationLBL_Window = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.NewFindingRemediationLBL_Window.setMaximumSize(QtCore.QSize(130, 16777215))
        self.NewFindingRemediationLBL_Window.setObjectName("NewFindingRemediationLBL_Window")
        self.verticalLayout_9.addWidget(self.NewFindingRemediationLBL_Window)
        self.NewFindingRemediationTextEdit_Window = QtWidgets.QTextEdit(self.scrollAreaWidgetContents_2)
        self.NewFindingRemediationTextEdit_Window.setMaximumSize(QtCore.QSize(500, 80))
        self.NewFindingRemediationTextEdit_Window.setObjectName("NewFindingRemediationTextEdit_Window")
        self.verticalLayout_9.addWidget(self.NewFindingRemediationTextEdit_Window)
        self.verticalLayout_29.addLayout(self.verticalLayout_9)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem6)
        self.FilenameLBL = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.FilenameLBL.setObjectName("FilenameLBL")
        self.horizontalLayout_10.addWidget(self.FilenameLBL)
        self.NameFileLineEdit_Window = QtWidgets.QLineEdit(self.scrollAreaWidgetContents_2)
        self.NameFileLineEdit_Window.setObjectName("NameFileLineEdit_Window")
        self.horizontalLayout_10.addWidget(self.NameFileLineEdit_Window)
        self.ExportInformationtoReportBTN_Window = QtWidgets.QPushButton(self.scrollAreaWidgetContents_2)
        self.ExportInformationtoReportBTN_Window.setMaximumSize(QtCore.QSize(200, 30))
        self.ExportInformationtoReportBTN_Window.setObjectName("ExportInformationtoReportBTN_Window")
        self.horizontalLayout_10.addWidget(self.ExportInformationtoReportBTN_Window)
        self.verticalLayout_29.addLayout(self.horizontalLayout_10)
        self.verticalLayout_39.addLayout(self.verticalLayout_29)
        self.verticalLayout_40.addLayout(self.verticalLayout_39)
        spacerItem7 = QtWidgets.QSpacerItem(20, 0, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_40.addItem(spacerItem7)
        self.scrollArea_2.setWidget(self.scrollAreaWidgetContents_2)
        self.verticalLayout_35.addWidget(self.scrollArea_2)
        self.horizontalLayout_9.addLayout(self.verticalLayout_35)
        self.verticalLayout_36.addLayout(self.horizontalLayout_9)
        self.verticalLayout_37.addLayout(self.verticalLayout_36)
        self.horizontalLayout_12.addLayout(self.verticalLayout_37)
        self.line_5 = QtWidgets.QFrame(TestOverviewWindow)
        self.line_5.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.horizontalLayout_12.addWidget(self.line_5)
        self.verticalLayout_27 = QtWidgets.QVBoxLayout()
        self.verticalLayout_27.setObjectName("verticalLayout_27")
        self.SummariesScrollAreaLBL = QtWidgets.QLabel(TestOverviewWindow)
        self.SummariesScrollAreaLBL.setMaximumSize(QtCore.QSize(200, 30))
        font = QtGui.QFont()
        font.setFamily("Eras Bold ITC")
        font.setPointSize(15)
        self.SummariesScrollAreaLBL.setFont(font)
        self.SummariesScrollAreaLBL.setObjectName("SummariesScrollAreaLBL")
        self.verticalLayout_27.addWidget(self.SummariesScrollAreaLBL)
        self.scrollArea = QtWidgets.QScrollArea(TestOverviewWindow)
        self.scrollArea.setMinimumSize(QtCore.QSize(650, 800))
        self.scrollArea.setMaximumSize(QtCore.QSize(650, 900))
        self.scrollArea.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.scrollArea.setFrameShadow(QtWidgets.QFrame.Plain)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 633, 1178))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_24 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_24.setObjectName("verticalLayout_24")
        self.verticalLayout_23 = QtWidgets.QVBoxLayout()
        self.verticalLayout_23.setObjectName("verticalLayout_23")
        self.ExecutiveSummaryLBL = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.ExecutiveSummaryLBL.setMinimumSize(QtCore.QSize(120, 20))
        self.ExecutiveSummaryLBL.setMaximumSize(QtCore.QSize(120, 20))
        self.ExecutiveSummaryLBL.setObjectName("ExecutiveSummaryLBL")
        self.verticalLayout_23.addWidget(self.ExecutiveSummaryLBL)
        self.ExecutiveSummaryTextEdit_Window = QtWidgets.QTextEdit(self.scrollAreaWidgetContents)
        self.ExecutiveSummaryTextEdit_Window.setMinimumSize(QtCore.QSize(600, 120))
        self.ExecutiveSummaryTextEdit_Window.setMaximumSize(QtCore.QSize(600, 120))
        self.ExecutiveSummaryTextEdit_Window.setObjectName("ExecutiveSummaryTextEdit_Window")
        self.verticalLayout_23.addWidget(self.ExecutiveSummaryTextEdit_Window)
        self.verticalLayout_24.addLayout(self.verticalLayout_23)
        self.verticalLayout_22 = QtWidgets.QVBoxLayout()
        self.verticalLayout_22.setObjectName("verticalLayout_22")
        self.ScopeLBL = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.ScopeLBL.setMinimumSize(QtCore.QSize(50, 20))
        self.ScopeLBL.setMaximumSize(QtCore.QSize(50, 20))
        self.ScopeLBL.setObjectName("ScopeLBL")
        self.verticalLayout_22.addWidget(self.ScopeLBL)
        self.ScopeTextEdit_Window = QtWidgets.QTextEdit(self.scrollAreaWidgetContents)
        self.ScopeTextEdit_Window.setMinimumSize(QtCore.QSize(600, 120))
        self.ScopeTextEdit_Window.setMaximumSize(QtCore.QSize(600, 120))
        self.ScopeTextEdit_Window.setObjectName("ScopeTextEdit_Window")
        self.verticalLayout_22.addWidget(self.ScopeTextEdit_Window)
        self.verticalLayout_24.addLayout(self.verticalLayout_22)
        self.verticalLayout_21 = QtWidgets.QVBoxLayout()
        self.verticalLayout_21.setObjectName("verticalLayout_21")
        self.ProjectObjectivesLBL = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.ProjectObjectivesLBL.setMinimumSize(QtCore.QSize(120, 20))
        self.ProjectObjectivesLBL.setMaximumSize(QtCore.QSize(120, 20))
        self.ProjectObjectivesLBL.setObjectName("ProjectObjectivesLBL")
        self.verticalLayout_21.addWidget(self.ProjectObjectivesLBL)
        self.ProjectObjectivesTextEdit_Window = QtWidgets.QTextEdit(self.scrollAreaWidgetContents)
        self.ProjectObjectivesTextEdit_Window.setMinimumSize(QtCore.QSize(600, 120))
        self.ProjectObjectivesTextEdit_Window.setMaximumSize(QtCore.QSize(600, 120))
        self.ProjectObjectivesTextEdit_Window.setObjectName("ProjectObjectivesTextEdit_Window")
        self.verticalLayout_21.addWidget(self.ProjectObjectivesTextEdit_Window)
        self.verticalLayout_24.addLayout(self.verticalLayout_21)
        self.verticalLayout_20 = QtWidgets.QVBoxLayout()
        self.verticalLayout_20.setObjectName("verticalLayout_20")
        self.AssumptionsLBL = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.AssumptionsLBL.setMinimumSize(QtCore.QSize(100, 20))
        self.AssumptionsLBL.setMaximumSize(QtCore.QSize(100, 20))
        self.AssumptionsLBL.setObjectName("AssumptionsLBL")
        self.verticalLayout_20.addWidget(self.AssumptionsLBL)
        self.AssumptionTextEdit_Window = QtWidgets.QTextEdit(self.scrollAreaWidgetContents)
        self.AssumptionTextEdit_Window.setMinimumSize(QtCore.QSize(600, 120))
        self.AssumptionTextEdit_Window.setMaximumSize(QtCore.QSize(600, 120))
        self.AssumptionTextEdit_Window.setObjectName("AssumptionTextEdit_Window")
        self.verticalLayout_20.addWidget(self.AssumptionTextEdit_Window)
        self.verticalLayout_24.addLayout(self.verticalLayout_20)
        self.verticalLayout_19 = QtWidgets.QVBoxLayout()
        self.verticalLayout_19.setObjectName("verticalLayout_19")
        self.SummaryofFindingsLBL = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.SummaryofFindingsLBL.setMinimumSize(QtCore.QSize(120, 20))
        self.SummaryofFindingsLBL.setMaximumSize(QtCore.QSize(120, 20))
        self.SummaryofFindingsLBL.setObjectName("SummaryofFindingsLBL")
        self.verticalLayout_19.addWidget(self.SummaryofFindingsLBL)
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.verticalLayout_19.addLayout(self.horizontalLayout_15)
        self.SummaryFindingsDB_Window = QtWidgets.QTableWidget(self.scrollAreaWidgetContents)
        self.SummaryFindingsDB_Window.setMinimumSize(QtCore.QSize(600, 200))
        self.SummaryFindingsDB_Window.setMaximumSize(QtCore.QSize(600, 200))
        self.SummaryFindingsDB_Window.setObjectName("SummaryFindingsDB_Window")
        self.SummaryFindingsDB_Window.setColumnCount(3)
        self.SummaryFindingsDB_Window.setRowCount(1)
        item = QtWidgets.QTableWidgetItem()
        self.SummaryFindingsDB_Window.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.SummaryFindingsDB_Window.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.SummaryFindingsDB_Window.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.SummaryFindingsDB_Window.setHorizontalHeaderItem(2, item)
        self.verticalLayout_19.addWidget(self.SummaryFindingsDB_Window)
        self.verticalLayout_24.addLayout(self.verticalLayout_19)
        self.verticalLayout_18 = QtWidgets.QVBoxLayout()
        self.verticalLayout_18.setObjectName("verticalLayout_18")
        self.SummaryofRecommendationLBL = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.SummaryofRecommendationLBL.setMinimumSize(QtCore.QSize(160, 20))
        self.SummaryofRecommendationLBL.setMaximumSize(QtCore.QSize(160, 20))
        self.SummaryofRecommendationLBL.setObjectName("SummaryofRecommendationLBL")
        self.verticalLayout_18.addWidget(self.SummaryofRecommendationLBL)
        self.SummaryofRecommendationTextEdit_Window = QtWidgets.QTextEdit(self.scrollAreaWidgetContents)
        self.SummaryofRecommendationTextEdit_Window.setMinimumSize(QtCore.QSize(600, 120))
        self.SummaryofRecommendationTextEdit_Window.setMaximumSize(QtCore.QSize(600, 120))
        self.SummaryofRecommendationTextEdit_Window.setObjectName("SummaryofRecommendationTextEdit_Window")
        self.verticalLayout_18.addWidget(self.SummaryofRecommendationTextEdit_Window)
        self.verticalLayout_24.addLayout(self.verticalLayout_18)
        self.verticalLayout_17 = QtWidgets.QVBoxLayout()
        self.verticalLayout_17.setObjectName("verticalLayout_17")
        self.MethodologyLBL = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.MethodologyLBL.setMinimumSize(QtCore.QSize(160, 20))
        self.MethodologyLBL.setMaximumSize(QtCore.QSize(160, 20))
        self.MethodologyLBL.setObjectName("MethodologyLBL")
        self.verticalLayout_17.addWidget(self.MethodologyLBL)
        self.MethodologyTextEdit_Window = QtWidgets.QTextEdit(self.scrollAreaWidgetContents)
        self.MethodologyTextEdit_Window.setMinimumSize(QtCore.QSize(600, 120))
        self.MethodologyTextEdit_Window.setMaximumSize(QtCore.QSize(600, 120))
        self.MethodologyTextEdit_Window.setObjectName("MethodologyTextEdit_Window")
        self.verticalLayout_17.addWidget(self.MethodologyTextEdit_Window)
        self.verticalLayout_24.addLayout(self.verticalLayout_17)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout_27.addWidget(self.scrollArea)
        spacerItem8 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_27.addItem(spacerItem8)
        self.horizontalLayout_12.addLayout(self.verticalLayout_27)
        self.verticalLayout_38.addLayout(self.horizontalLayout_12)

        self.retranslateUi(TestOverviewWindow)
        QtCore.QMetaObject.connectSlotsByName(TestOverviewWindow)
        
        #Load Findings Button
        self.LoadFindings_WindowBTN.clicked.connect(self.Findings_List)
        #disabling searchbar button
        self.SearchBarBTN.setEnabled(False)
        self.searchbarLineEdit.textChanged.connect(self.disabledButton)
        #searching function
        self.SearchBarBTN.clicked.connect(self.handleButton)

         #when clicked in cell, select all row instead (Findings Database)
        self.FindingsListWidget_Window.itemSelectionChanged.connect(self.on_selection_changed)

        #Report Button
        self.ExportInformationtoReportBTN_Window.clicked.connect(self.Extracting_Report)
    def retranslateUi(self, TestOverviewWindow):
        _translate = QtCore.QCoreApplication.translate
        TestOverviewWindow.setWindowTitle(_translate("TestOverviewWindow", "Test Information Overview"))
        self.ReportLBL_Window.setText(_translate("TestOverviewWindow", "Report"))
        self.InformationOverviewTestIDLBL.setText(_translate("TestOverviewWindow", "Test_ID:"))
        self.ReportTitleLBL_2_Window.setText(_translate("TestOverviewWindow", "Report Title"))
        self.AssessmentTypeLBL_2_Window.setText(_translate("TestOverviewWindow", "Assessment Type"))
        self.ScoringTypeLBL_2_Window.setText(_translate("TestOverviewWindow", "Scoring Type"))
        self.FullCompNameLBL_2_Window.setText(_translate("TestOverviewWindow", "Full Company Name"))
        self.ShortCompNameLBL_2_Window.setText(_translate("TestOverviewWindow", "Short Company Name"))
        self.ContactCompany_Window.setText(_translate("TestOverviewWindow", "Contact Company"))
        self.ContactTitleLBL_2_Window.setText(_translate("TestOverviewWindow", "Contact Title"))
        self.ContactNameLBL_2_Window.setText(_translate("TestOverviewWindow", "Contact Name"))
        self.ContactTelephoneLBL_Window.setText(_translate("TestOverviewWindow", "Contact Telephone"))
        self.ContactEmailLBL_2_Window.setText(_translate("TestOverviewWindow", "Contact Email Address"))
        self.CompWebsiteLBL_2_Window.setText(_translate("TestOverviewWindow", "Company Website"))
        self.CompAddressLBL_2_Window.setText(_translate("TestOverviewWindow", "Company Address"))
        self.CompCityLBL_2_Window.setText(_translate("TestOverviewWindow", "Company City"))
        self.StateLBL_2_Window.setText(_translate("TestOverviewWindow", "State"))
        self.CompPostCodeLBL_2_Window.setText(_translate("TestOverviewWindow", "Company Post Code"))
        self.TesterLBL_Window.setText(_translate("TestOverviewWindow", "Tester"))
        self.ConsultantCompanyNameLBL_Window.setText(_translate("TestOverviewWindow", "Company Name: "))
        self.ConsultantTitleLBL_Window.setText(_translate("TestOverviewWindow", "Title:"))
        self.TesterName_NewWindowLBL.setText(_translate("TestOverviewWindow", "Tester Name:"))
        self.ConsultantTelephoneLBL_Window.setText(_translate("TestOverviewWindow", "Telephone:"))
        self.ConsultantEmailLBL_Window.setText(_translate("TestOverviewWindow", "E-mail:"))
        self.ConsultantAddressLBL_Window.setText(_translate("TestOverviewWindow", "Business Address:"))
        self.ConsultantCityLBL_Window.setText(_translate("TestOverviewWindow", "City:"))
        self.ConsultantWebsiteLBL_Window.setText(_translate("TestOverviewWindow", "Website:"))
        self.CVEInformation_Window.setText(_translate("TestOverviewWindow", "CVE Information:"))
        self.CVENameLBLDisplay_Window.setText(_translate("TestOverviewWindow", "CVE Name:"))
        self.CVSSLBLDisplay_Window.setText(_translate("TestOverviewWindow", "CVSS:"))
        self.CVEDateLBLDisplay_Window.setText(_translate("TestOverviewWindow", "CVE Date:"))
        self.CVECriticalRatingLBLDisplay_Window.setText(_translate("TestOverviewWindow", "CVE Critical Rating:"))
        self.CVEDescriptionLBLDisplay_Window.setText(_translate("TestOverviewWindow", "CVE Description:"))
        self.CVERemediationLBLDisplay_Window.setText(_translate("TestOverviewWindow", "CVE Remediation"))
        self.FindingsInformation_Window.setText(_translate("TestOverviewWindow", "Findings Information:"))
        self.selectyourfinding_Window.setText(_translate("TestOverviewWindow", "Select your finding:"))
        self.LoadFindings_WindowBTN.setText(_translate("TestOverviewWindow", "Load Findings"))
        self.searchLBL.setText(_translate("TestOverviewWindow", "Search:"))
        self.SearchBarBTN.setText(_translate("TestOverviewWindow", "Search"))
        self.NameYourFindingLBL_Window.setText(_translate("TestOverviewWindow", "Findings Name:"))
        self.NewFindingCriticalityLBL_Window.setText(_translate("TestOverviewWindow", "Findings Criticality:"))
        self.NewfindingTypeLBL_Window.setText(_translate("TestOverviewWindow", "Findings Type"))
        self.NewFindingDescriptionLBL_Window.setText(_translate("TestOverviewWindow", "Findings Description"))
        self.NewFindingRemediationLBL_Window.setText(_translate("TestOverviewWindow", "Findings Remediation"))
        self.FilenameLBL.setText(_translate("TestOverviewWindow", "File Name:"))
        self.ExportInformationtoReportBTN_Window.setText(_translate("TestOverviewWindow", "Export Information to Report"))
        self.SummariesScrollAreaLBL.setText(_translate("TestOverviewWindow", "Summaries"))
        self.ExecutiveSummaryLBL.setText(_translate("TestOverviewWindow", "Executive Summary:"))
        self.ScopeLBL.setText(_translate("TestOverviewWindow", "Scope:"))
        self.ProjectObjectivesLBL.setText(_translate("TestOverviewWindow", "Project Objectives:"))
        self.ProjectObjectivesTextEdit_Window.setHtml(_translate("TestOverviewWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.AssumptionsLBL.setText(_translate("TestOverviewWindow", "Assumption\'s"))
        self.SummaryofFindingsLBL.setText(_translate("TestOverviewWindow", "Summary of Findings:"))
        item = self.SummaryFindingsDB_Window.verticalHeaderItem(0)
        item.setText(_translate("TestOverviewWindow", "1"))
        item = self.SummaryFindingsDB_Window.horizontalHeaderItem(0)
        item.setText(_translate("TestOverviewWindow", "ID"))
        item = self.SummaryFindingsDB_Window.horizontalHeaderItem(1)
        item.setText(_translate("TestOverviewWindow", "Description"))
        item = self.SummaryFindingsDB_Window.horizontalHeaderItem(2)
        item.setText(_translate("TestOverviewWindow", "Risk"))
        self.SummaryofRecommendationLBL.setText(_translate("TestOverviewWindow", "Summary of Recommendations:"))
        self.MethodologyLBL.setText(_translate("TestOverviewWindow", "Methodology"))


    #display findings database in List Widget
    def  Findings_List(self):
        conn = sqlite3.connect('Main_Database.db')

        curser= conn.cursor()
        curser.execute("SELECT Name FROM Findings")
        hu= curser.fetchall()
        self.FindingsListWidget_Window.clear()
        for i in range(len(hu)):
            item= QtWidgets.QListWidgetItem(hu[i][0])
            self.FindingsListWidget_Window.addItem(item)

    #Only enabling Search Button if user input text into search bar
    def disabledButton(self):
        if len(self.searchbarLineEdit.text()) > 0:
            self.SearchBarBTN.setEnabled(True)
        else:
            self.SearchBarBTN.setEnabled(False)
            self.LoadFindings_WindowBTN.click()

            
    #Search Bar in Database
    def handleButton(self):
        searchbar = self.searchbarLineEdit.text()

        for rowIndex in range(self.FindingsListWidget_Window.count()):
            twItem = self.FindingsListWidget_Window.item(rowIndex)

            if twItem.text() == str(searchbar):
                self.FindingsListWidget_Window.setRowHidden(rowIndex, False)
            else:
                self.FindingsListWidget_Window.setRowHidden(rowIndex, True)


    def on_selection_changed(self):
        whole_row = self.FindingsListWidget_Window.currentRow() # Index of Row
        name = self.FindingsListWidget_Window.item(whole_row)
        if name is not None:
            
            name = name.text() # content of this
            
        conn = sqlite3.connect('Main_Database.db')
        c = conn.cursor()
        querying1 = c.execute('SELECT Name, Criticality, Type, Description, Remediation FROM Findings WHERE Name=?',(name,))

        for (Name, Criticality, Type, Description, Remediation) in querying1.fetchall():
            self.NameYourFindingTextEdit_Window.setText(str(Name))
            self.NewFindingCriticalityTextEdit_Window.setText(str(Criticality))
            self.NewfindingTypeTextEdit_Window.setText(str(Type))
            self.NewFindingDescriptionTextEdit_Window.setText(str(Description))
            self.NewFindingRemediationTextEdit_Window.setText(str(Remediation))

    def Extracting_Report(self):
        """Report Information """
        Report_Title = self.ReportTitleBox_2_Window.text()
        AssessmentType = self.AssessmentTypeBox_2_Window.text()
        ScoringType = self.ScoringTypeBox_2_Window.text()
        FullCompanyName = self.FullCompNameBox_2_Window.text()
        ShortCompanyName = self.ShortCompNameBox_2_Window.text()
        
        """Contact Information """
        ContactTitle =self.ContactTitleBox_2_Window.text()
        ContactName =self.ContactNameBox_2_Window.text()
        ContactTelephone =self.ContactTelephoneBox_Window.text()
        ContactEmailAddress =self.ContactEmailBox_2_Window.text()
        ContactWebsite =self.CompWebsiteBox_2_Window.text()
        ContactAddress =self.CompAddressBox_2_Window.text()
        ContactCity =self.CompCityBox_2_Window.text()
        ContactState =self.StateBox_2_Window.text()
        ContactPostCode =self.CompPostCodeBox_2_Window.text()

        """Tester Information """
        TesterCompanyName =self.ConsultantCompanyNameBox_Window.text()
        TesterContactName =self.TesterName_NewWindow.text()
        TesterTitle =self.ConsultantTitleBox_Window.text()
        TesterTelephone =self.ConsultantTelephoneBox_Window.text()
        TesterEmail =self.ConsultantEmailBox_Window.text()
        TesterBusinessAddress =self.ConsultantBusinessAddressBox_Window.text()
        TesterCity =self.ConsultantCityBox_Window.text()
        TesterWebsite =self.ConsultantWebsiteBox_Window.text()

        """CVE"""
        CVEName = self.CVENameTextEdit_Window.toPlainText()
        CVSS = self.CVSSTextEdit_Window.toPlainText()
        CVEDate = self.CVEDateTextEdit_Window.toPlainText()
        CVECritical_Rating = self.CVECriticalRatingTextEdit_Window.toPlainText()
        CVEDescription = self.CVEDescriptionTextEdit_Window.toPlainText()
        CVERemediation = self.CVERemediationTextEdit_Window.toPlainText()

        """Findings"""
        name = self.NameYourFindingTextEdit_Window.toPlainText()
        description = self.NewFindingDescriptionTextEdit_Window.toPlainText()
        remediation = self.NewFindingRemediationTextEdit_Window.toPlainText()
        criticality = self.NewFindingCriticalityTextEdit_Window.toPlainText()
        type_finding = self.NewfindingTypeTextEdit_Window.toPlainText()

        """Summaries"""
        Executive_Summary = self.ExecutiveSummaryTextEdit_Window.toPlainText()
        Scope = self.ScopeTextEdit_Window.toPlainText()
        Project_Objectives = self.ProjectObjectivesTextEdit_Window.toPlainText()
        Assumptions = self.AssumptionTextEdit_Window.toPlainText()
        Summary_Recommendations = self.SummaryofRecommendationTextEdit_Window.toPlainText()
        Methodology = self.MethodologyTextEdit_Window.toPlainText()

        """File Name"""
        FileName = self.NameFileLineEdit_Window.text()

        """Opening DB"""
        conn = sqlite3.connect('Main_Database.db')
        c = conn.cursor()
        try:
            if (str(self.InformationOverviewTestIDLineEdit.text()) and
                str(self.ReportTitleBox_2_Window.text()) and
                str(self.AssessmentTypeBox_2_Window.text()) and
                str(self.ScoringTypeBox_2_Window.text()) and
                str(self.FullCompNameBox_2_Window.text()) and
                str(self.ShortCompNameBox_2_Window.text()) and
                str(self.ContactTitleBox_2_Window.text()) and
                str(self.ContactNameBox_2_Window.text()) and
                str(self.ContactTelephoneBox_Window.text()) and
                str(self.ContactEmailBox_2_Window.text()) and
                str(self.CompWebsiteBox_2_Window.text()) and
                str(self.CompAddressBox_2_Window.text()) and
                str(self.CompCityBox_2_Window.text()) and
                str(self.StateBox_2_Window.text()) and
                str(self.CompPostCodeBox_2_Window.text()) and
                str(self.ConsultantCompanyNameBox_Window.text()) and
                str(self.TesterName_NewWindow.text()) and
                str(self.ConsultantTitleBox_Window.text()) and
                str(self.ConsultantTelephoneBox_Window.text()) and
                str(self.ConsultantEmailBox_Window.text()) and
                str(self.ConsultantBusinessAddressBox_Window.text()) and
                str(self.ConsultantCityBox_Window.text()) and
                str(self.ConsultantWebsiteBox_Window.text()) and        
                str(self.CVENameTextEdit_Window.toPlainText()) and
                str(self.CVSSTextEdit_Window.toPlainText()) and
                str(self.CVEDateTextEdit_Window.toPlainText()) and
                str(self.CVECriticalRatingTextEdit_Window.toPlainText()) and
                str(self.CVEDescriptionTextEdit_Window.toPlainText()) and
                str(self.CVERemediationTextEdit_Window.toPlainText()) and
                str(self.NameYourFindingTextEdit_Window.toPlainText()) and
                str(self.NewFindingDescriptionTextEdit_Window.toPlainText()) and
                str(self.NewFindingRemediationTextEdit_Window.toPlainText()) and
                str(self.NewFindingCriticalityTextEdit_Window.toPlainText()) and
                str(self.NewfindingTypeTextEdit_Window.toPlainText()) and
                str(self.ExecutiveSummaryTextEdit_Window.toPlainText()) and
                str(self.ScopeTextEdit_Window.toPlainText()) and
                str(self.ProjectObjectivesTextEdit_Window.toPlainText()) and
                str(self.AssumptionTextEdit_Window.toPlainText()) and
                str(self.SummaryofRecommendationTextEdit_Window.toPlainText()) and
                str(self.MethodologyTextEdit_Window.toPlainText()) and
                str(self.NameFileLineEdit_Window.text()))  != "":

                doc = Document()
                section = doc.sections[0]
                header = section.header
                paragraph = header.paragraphs[0]
                paragraph.text = Report_Title,"\t","\t",TesterCompanyName
                
                #adding the Report Title to the document
                doc.add_heading(Report_Title, level=0)
                #adding the assessment type, scoring type, full comp and short comp name into the main body
                doc.add_heading("Report Information", level=1)
                As_Type = doc.add_paragraph()
                As_Type.add_run('Assessment Type: ').bold = True
                As_Type.add_run(AssessmentType)
                
                Score_Para = doc.add_paragraph()
                Score_Para.add_run('Scoring Type: ').bold = True
                Score_Para.add_run(ScoringType)
                
                Full_Comp_Name_Para = doc.add_paragraph()
                Full_Comp_Name_Para.add_run('Full Company Name: ').bold = True
                Full_Comp_Name_Para.add_run(FullCompanyName)
                
                Short_Compname_Para = doc.add_paragraph()
                Short_Compname_Para.add_run('Short Company Name: ').bold = True
                Short_Compname_Para.add_run(ShortCompanyName)

                #making a table for contact and tester
                doc.add_heading("Contact and Tester Information", level=1)
                table = doc.add_table(rows=2, cols=2)
                hdr_cells = table.rows[0].cells
                hdr_cells[0].text = 'Contact Information'
                hdr_cells[1].text = 'Tester Information'


                row_cells = table.rows[1].cells
                row_cells[0].text = ('Contact Title: ' + '\t' + '\t' + ContactTitle + '\n' + 'Contact Name: ' + '\t' + '\t'  + ContactName + '\n' + 'Contact Telephone: '+ '\t'  + ContactTelephone + '\n' + 'Contact Email: '  + ContactEmailAddress + '\n'
                'Contact Website: ' + '\t' + ContactWebsite + '\n' + 'Contact Address: '+ '\t' + ContactAddress + '\n' + 'Contact City: ' + '\t' + '\t' + ContactCity + '\n' + 'Contact State: ' + '\t'+ '\t'  + ContactState + '\n'
                'Contact Postcode: ' + '\t'+ ContactPostCode)

                row_cells[1].text = ('Tester Title: ' + '\t'  + '\t' + TesterTitle + '\n' +  'Tester Name: ' + '\t'  + '\t' + TesterContactName + '\n' + 'Company Name: ' +'\t'+ TesterCompanyName + '\n'
                                     'Tester Telephone: ' + '\t' + TesterTelephone + '\n' + 'Tester Email: ' + TesterEmail + '\n' + 'Tester Address: ' + '\t'  + '\t' + TesterBusinessAddress +  '\n'
                                     'Tester City: ' + '\t'  + '\t' + TesterCity + '\n' + 'Tester Website: ' +  '\t' +TesterWebsite)

                doc.add_page_break()

                #adding the Summaries section
                doc.add_heading("Executive Summary", level=1)
                doc.add_paragraph(Executive_Summary)
                doc.add_heading('Scope', level=1)
                doc.add_paragraph(Scope)
                doc.add_heading('Project Objectives', level=1)
                doc.add_paragraph(Project_Objectives)
                doc.add_heading('Assumptions', level=1)
                doc.add_paragraph(Assumptions)
         
                #making a table for contact and tester
                doc.add_heading("Findings Summary", level=1)
                table_findings = doc.add_table(rows=1, cols=3)
                hdr_cells1 = table_findings.rows[0].cells
                hdr_cells1[0].width = Cm(1)
                hdr_cells1[0].text = 'ID'
                hdr_cells1[1].width = Cm(14)
                hdr_cells1[1].text = 'Description'
                hdr_cells1[2].width = Cm(1)
                hdr_cells1[2].text = 'Risk'
                test_id1 = self.InformationOverviewTestIDLineEdit.text()
                c.execute('SELECT Summary_Findings_Name, Summary_Findings_Desc, Summary_Findings_Risk FROM Findings_Summaries WHERE Test_ID=?', [test_id1])
                for colm_name, colm_desc, colm_risk in c.fetchall():
                    cells = table_findings.add_row().cells
                    cells[0].text = (str(colm_name))
                    cells[1].text = (str(colm_desc))
                    cells[2].text = (str(colm_risk))

                    
                doc.add_page_break()
                
                doc.add_heading('Recommendation', level=1)
                doc.add_paragraph(Summary_Recommendations)
                doc.add_heading('Methodology', level=1)
                doc.add_paragraph(Methodology)
                
                doc.add_page_break()
                
                #adding the CVE
                doc.add_heading("CVE Information", level=1)
                doc.add_heading('CVE Name', level=2)
                doc.add_paragraph(CVEName)
                doc.add_heading('CVE Date', level=2)
                doc.add_paragraph(CVEDate)
                doc.add_heading('CVE Critical Rating', level=2)
                doc.add_paragraph(CVECritical_Rating)
                doc.add_heading('CVE Description', level=2)
                doc.add_paragraph(CVEDescription)
                doc.add_heading('CVE Remediation', level=2)
                doc.add_paragraph(CVERemediation)                

                #adding Findings
                doc.add_heading("Findings Information", level=1)
                doc.add_heading('Findings Name', level=2)
                doc.add_paragraph(name)
                doc.add_heading('Findings Criticality', level=2)
                doc.add_paragraph(criticality)
                doc.add_heading('Findings  Type', level=2)
                doc.add_paragraph(type_finding)
                doc.add_heading('Findings Description', level=2)
                doc.add_paragraph(description)
                doc.add_heading('Findings Remediation', level=2)
                doc.add_paragraph(remediation)   

                doc.save(FileName+'.docx')
        except Exception as e:
            print(e)
            
 #Just displays errors instead of ommiting them

sys._excepthook = sys.excepthook 
def exception_hook(exctype, value, traceback):
    print(exctype, value, traceback)
    sys._excepthook(exctype, value, traceback) 
    sys.exit(1) 
sys.excepthook = exception_hook 



if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    TestOverviewWindow = QtWidgets.QDialog()
    ui = Ui_TestOverviewWindow()
    ui.setupUi(TestOverviewWindow)
    TestOverviewWindow.show()
    sys.exit(app.exec_())
